# github pages
name: vrc-tenki-yoho

on:
  # 一日2回のスケジュールを気象庁の更新に合わせて記述する
  push:
    branches:
      - master

jobs:
  load-image:
    name: load image
    runs-on: ubuntu-latest
    steps:
      - name: mkdir
        run: mkdir public
      - name: download image telop-today
        run: wget -np "https://www.jma.go.jp/jp/yoho/images/000_telop_today.png"
        run: wget -np "https://www.jma.go.jp/jp/yoho/images/000_temp_today.png"
      - name: deploy
        # https://github.com/peaceiris/actions-gh-pages
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{secrets.ACTIONS_DEPLOY_KEY}}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: public